spring.application.name=Gruhani
spring.datasource.url=jdbc:postgresql://localhost:5432/Gruhanidb
spring.datasource.username=postgres
spring.datasource.password=@Lachhu19
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8085}
spring.security.oauth2.client.registration.google.client-id=297151085641-hnppfnd4pmd33j8t39gjjtk9g9qo4tuq.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=

google.credentials.path=
whatsapp.access-token
whatsapp.phone-number-id=7

