spring.application.name=Gruhani
spring.datasource.url=jdbc:postgresql://localhost:5432/Gruhanidb
spring.datasource.username=postgres
spring.datasource.password=@Lachhu19
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8085}
spring.security.oauth2.client.registration.google.client-id=297151085641-hnppfnd4pmd33j8t39gjjtk9g9qo4tuq.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

google.credentials.path=C:/Users/HP/Downloads/phonic-bivouac-463710-e0-09285cd4cf49.json
whatsapp.access-token=EAAUfU1hBPl4BPK8sprCovZCpMZB5nOXnMEQei2yUerftnC5xfTemTgWxM76QLWdfEJNkNhrFA9UPKCNUeQa8g9ZA1i8jSH7fkLLxy5lcKtYZAn1TSLMabsH60GEfnNZAo2rpnZCHZAmm4efgebCib1GemLHZCpJTqVXBz2wHWBTTIAoWqxFVv1ZAjsAKaSskpKJ9cU6VuXNFvYlk1NmWS5oR0s1UpDmCgmJWzlZCipqgxXZBS0ZD
whatsapp.phone-number-id=756788014180774

spring.jpa.hibernate.ddl-auto=update
