spring.application.name=Gruhani
spring.datasource.url=jdbc:postgresql://localhost:5432/Gruhanidb
spring.datasource.username=postgres
spring.datasource.password=@Lachhu19
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8085

spring.jpa.hibernate.ddl-auto=update
